/**
 * Copyright 2017 VMware, Inc.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto
package io.logz.listener.inputs.prometheus.protocol;

public final class Types {
    private Types() { }
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface SampleOrBuilder extends
            // @@protoc_insertion_point(interface_extends:prometheus.Sample)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional double value = 1;</code>
         */
        double getValue();

        /**
         * <pre>
         * Asaf: Renamed to TimestampMillis from Timestamp to clarify this is millisecond unit
         * </pre>
         *
         * <code>optional int64 timestampMillis = 2;</code>
         */
        long getTimestampMillis();
    }
    /**
     * Protobuf type {@code prometheus.Sample}
     */
    public  static final class Sample extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:prometheus.Sample)
            SampleOrBuilder {
        // Use Sample.newBuilder() to construct.
        private Sample(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Sample() {
            value_ = 0D;
            timestampMillis_ = 0L;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }
        private Sample(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 9: {

                            value_ = input.readDouble();
                            break;
                        }
                        case 16: {

                            timestampMillis_ = input.readInt64();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Types.internal_static_prometheus_Sample_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Types.internal_static_prometheus_Sample_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Sample.class, Builder.class);
        }

        public static final int VALUE_FIELD_NUMBER = 1;
        private double value_;
        /**
         * <code>optional double value = 1;</code>
         */
        public double getValue() {
            return value_;
        }

        public static final int TIMESTAMPMILLIS_FIELD_NUMBER = 2;
        private long timestampMillis_;
        /**
         * <pre>
         * Asaf: Renamed to TimestampMillis from Timestamp to clarify this is millisecond unit
         * </pre>
         *
         * <code>optional int64 timestampMillis = 2;</code>
         */
        public long getTimestampMillis() {
            return timestampMillis_;
        }

        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (value_ != 0D) {
                output.writeDouble(1, value_);
            }
            if (timestampMillis_ != 0L) {
                output.writeInt64(2, timestampMillis_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (value_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(1, value_);
            }
            if (timestampMillis_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(2, timestampMillis_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Sample)) {
                return super.equals(obj);
            }
            Sample other = (Sample) obj;

            boolean result = true;
            result = result && (
                    Double.doubleToLongBits(getValue())
                            == Double.doubleToLongBits(
                            other.getValue()));
            result = result && (getTimestampMillis()
                    == other.getTimestampMillis());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            hash = (37 * hash) + VALUE_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    Double.doubleToLongBits(getValue()));
            hash = (37 * hash) + TIMESTAMPMILLIS_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getTimestampMillis());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Sample parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Sample parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Sample parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Sample parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Sample parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Sample parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static Sample parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static Sample parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static Sample parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Sample parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(Sample prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code prometheus.Sample}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:prometheus.Sample)
                SampleOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Types.internal_static_prometheus_Sample_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Types.internal_static_prometheus_Sample_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Sample.class, Builder.class);
            }

            // Construct using io.logz.listener.inputs.prometheus.protocol.Types.Sample.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            public Builder clear() {
                super.clear();
                value_ = 0D;

                timestampMillis_ = 0L;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Types.internal_static_prometheus_Sample_descriptor;
            }

            public Sample getDefaultInstanceForType() {
                return Sample.getDefaultInstance();
            }

            public Sample build() {
                Sample result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public Sample buildPartial() {
                Sample result = new Sample(this);
                result.value_ = value_;
                result.timestampMillis_ = timestampMillis_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Sample) {
                    return mergeFrom((Sample)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Sample other) {
                if (other == Sample.getDefaultInstance()) return this;
                if (other.getValue() != 0D) {
                    setValue(other.getValue());
                }
                if (other.getTimestampMillis() != 0L) {
                    setTimestampMillis(other.getTimestampMillis());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Sample parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Sample) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private double value_ ;
            /**
             * <code>optional double value = 1;</code>
             */
            public double getValue() {
                return value_;
            }
            /**
             * <code>optional double value = 1;</code>
             */
            public Builder setValue(double value) {

                value_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional double value = 1;</code>
             */
            public Builder clearValue() {

                value_ = 0D;
                onChanged();
                return this;
            }

            private long timestampMillis_ ;
            /**
             * <pre>
             * Asaf: Renamed to TimestampMillis from Timestamp to clarify this is millisecond unit
             * </pre>
             *
             * <code>optional int64 timestampMillis = 2;</code>
             */
            public long getTimestampMillis() {
                return timestampMillis_;
            }
            /**
             * <pre>
             * Asaf: Renamed to TimestampMillis from Timestamp to clarify this is millisecond unit
             * </pre>
             *
             * <code>optional int64 timestampMillis = 2;</code>
             */
            public Builder setTimestampMillis(long value) {

                timestampMillis_ = value;
                onChanged();
                return this;
            }
            /**
             * <pre>
             * Asaf: Renamed to TimestampMillis from Timestamp to clarify this is millisecond unit
             * </pre>
             *
             * <code>optional int64 timestampMillis = 2;</code>
             */
            public Builder clearTimestampMillis() {

                timestampMillis_ = 0L;
                onChanged();
                return this;
            }
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:prometheus.Sample)
        }

        // @@protoc_insertion_point(class_scope:prometheus.Sample)
        private static final Sample DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new Sample();
        }

        public static Sample getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Sample>
                PARSER = new com.google.protobuf.AbstractParser<Sample>() {
            public Sample parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Sample(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Sample> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<Sample> getParserForType() {
            return PARSER;
        }

        public Sample getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface TimeSeriesOrBuilder extends
            // @@protoc_insertion_point(interface_extends:prometheus.TimeSeries)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>repeated .prometheus.Label labels = 1;</code>
         */
        java.util.List<Label>
        getLabelsList();
        /**
         * <code>repeated .prometheus.Label labels = 1;</code>
         */
        Label getLabels(int index);
        /**
         * <code>repeated .prometheus.Label labels = 1;</code>
         */
        int getLabelsCount();
        /**
         * <code>repeated .prometheus.Label labels = 1;</code>
         */
        java.util.List<? extends LabelOrBuilder>
        getLabelsOrBuilderList();
        /**
         * <code>repeated .prometheus.Label labels = 1;</code>
         */
        LabelOrBuilder getLabelsOrBuilder(
                int index);

        /**
         * <code>repeated .prometheus.Sample samples = 2;</code>
         */
        java.util.List<Sample>
        getSamplesList();
        /**
         * <code>repeated .prometheus.Sample samples = 2;</code>
         */
        Sample getSamples(int index);
        /**
         * <code>repeated .prometheus.Sample samples = 2;</code>
         */
        int getSamplesCount();
        /**
         * <code>repeated .prometheus.Sample samples = 2;</code>
         */
        java.util.List<? extends SampleOrBuilder>
        getSamplesOrBuilderList();
        /**
         * <code>repeated .prometheus.Sample samples = 2;</code>
         */
        SampleOrBuilder getSamplesOrBuilder(
                int index);
    }
    /**
     * <pre>
     * TimeSeries represents samples and labels for a single time series.
     * </pre>
     *
     * Protobuf type {@code prometheus.TimeSeries}
     */
    public  static final class TimeSeries extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:prometheus.TimeSeries)
            TimeSeriesOrBuilder {
        // Use TimeSeries.newBuilder() to construct.
        private TimeSeries(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private TimeSeries() {
            labels_ = java.util.Collections.emptyList();
            samples_ = java.util.Collections.emptyList();
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }
        private TimeSeries(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                                labels_ = new java.util.ArrayList<Label>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            labels_.add(
                                    input.readMessage(Label.parser(), extensionRegistry));
                            break;
                        }
                        case 18: {
                            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                                samples_ = new java.util.ArrayList<Sample>();
                                mutable_bitField0_ |= 0x00000002;
                            }
                            samples_.add(
                                    input.readMessage(Sample.parser(), extensionRegistry));
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                    labels_ = java.util.Collections.unmodifiableList(labels_);
                }
                if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                    samples_ = java.util.Collections.unmodifiableList(samples_);
                }
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Types.internal_static_prometheus_TimeSeries_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Types.internal_static_prometheus_TimeSeries_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            TimeSeries.class, Builder.class);
        }

        public static final int LABELS_FIELD_NUMBER = 1;
        private java.util.List<Label> labels_;
        /**
         * <code>repeated .prometheus.Label labels = 1;</code>
         */
        public java.util.List<Label> getLabelsList() {
            return labels_;
        }
        /**
         * <code>repeated .prometheus.Label labels = 1;</code>
         */
        public java.util.List<? extends LabelOrBuilder>
        getLabelsOrBuilderList() {
            return labels_;
        }
        /**
         * <code>repeated .prometheus.Label labels = 1;</code>
         */
        public int getLabelsCount() {
            return labels_.size();
        }
        /**
         * <code>repeated .prometheus.Label labels = 1;</code>
         */
        public Label getLabels(int index) {
            return labels_.get(index);
        }
        /**
         * <code>repeated .prometheus.Label labels = 1;</code>
         */
        public LabelOrBuilder getLabelsOrBuilder(
                int index) {
            return labels_.get(index);
        }

        public static final int SAMPLES_FIELD_NUMBER = 2;
        private java.util.List<Sample> samples_;
        /**
         * <code>repeated .prometheus.Sample samples = 2;</code>
         */
        public java.util.List<Sample> getSamplesList() {
            return samples_;
        }
        /**
         * <code>repeated .prometheus.Sample samples = 2;</code>
         */
        public java.util.List<? extends SampleOrBuilder>
        getSamplesOrBuilderList() {
            return samples_;
        }
        /**
         * <code>repeated .prometheus.Sample samples = 2;</code>
         */
        public int getSamplesCount() {
            return samples_.size();
        }
        /**
         * <code>repeated .prometheus.Sample samples = 2;</code>
         */
        public Sample getSamples(int index) {
            return samples_.get(index);
        }
        /**
         * <code>repeated .prometheus.Sample samples = 2;</code>
         */
        public SampleOrBuilder getSamplesOrBuilder(
                int index) {
            return samples_.get(index);
        }

        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            for (int i = 0; i < labels_.size(); i++) {
                output.writeMessage(1, labels_.get(i));
            }
            for (int i = 0; i < samples_.size(); i++) {
                output.writeMessage(2, samples_.get(i));
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            for (int i = 0; i < labels_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, labels_.get(i));
            }
            for (int i = 0; i < samples_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, samples_.get(i));
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof TimeSeries)) {
                return super.equals(obj);
            }
            TimeSeries other = (TimeSeries) obj;

            boolean result = true;
            result = result && getLabelsList()
                    .equals(other.getLabelsList());
            result = result && getSamplesList()
                    .equals(other.getSamplesList());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            if (getLabelsCount() > 0) {
                hash = (37 * hash) + LABELS_FIELD_NUMBER;
                hash = (53 * hash) + getLabelsList().hashCode();
            }
            if (getSamplesCount() > 0) {
                hash = (37 * hash) + SAMPLES_FIELD_NUMBER;
                hash = (53 * hash) + getSamplesList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static TimeSeries parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static TimeSeries parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static TimeSeries parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static TimeSeries parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static TimeSeries parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static TimeSeries parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static TimeSeries parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static TimeSeries parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static TimeSeries parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static TimeSeries parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(TimeSeries prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * <pre>
         * TimeSeries represents samples and labels for a single time series.
         * </pre>
         *
         * Protobuf type {@code prometheus.TimeSeries}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:prometheus.TimeSeries)
                TimeSeriesOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Types.internal_static_prometheus_TimeSeries_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Types.internal_static_prometheus_TimeSeries_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                TimeSeries.class, Builder.class);
            }

            // Construct using io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                    getLabelsFieldBuilder();
                    getSamplesFieldBuilder();
                }
            }
            public Builder clear() {
                super.clear();
                if (labelsBuilder_ == null) {
                    labels_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                } else {
                    labelsBuilder_.clear();
                }
                if (samplesBuilder_ == null) {
                    samples_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000002);
                } else {
                    samplesBuilder_.clear();
                }
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Types.internal_static_prometheus_TimeSeries_descriptor;
            }

            public TimeSeries getDefaultInstanceForType() {
                return TimeSeries.getDefaultInstance();
            }

            public TimeSeries build() {
                TimeSeries result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public TimeSeries buildPartial() {
                TimeSeries result = new TimeSeries(this);
                int from_bitField0_ = bitField0_;
                if (labelsBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) == 0x00000001)) {
                        labels_ = java.util.Collections.unmodifiableList(labels_);
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    result.labels_ = labels_;
                } else {
                    result.labels_ = labelsBuilder_.build();
                }
                if (samplesBuilder_ == null) {
                    if (((bitField0_ & 0x00000002) == 0x00000002)) {
                        samples_ = java.util.Collections.unmodifiableList(samples_);
                        bitField0_ = (bitField0_ & ~0x00000002);
                    }
                    result.samples_ = samples_;
                } else {
                    result.samples_ = samplesBuilder_.build();
                }
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof TimeSeries) {
                    return mergeFrom((TimeSeries)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(TimeSeries other) {
                if (other == TimeSeries.getDefaultInstance()) return this;
                if (labelsBuilder_ == null) {
                    if (!other.labels_.isEmpty()) {
                        if (labels_.isEmpty()) {
                            labels_ = other.labels_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                        } else {
                            ensureLabelsIsMutable();
                            labels_.addAll(other.labels_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.labels_.isEmpty()) {
                        if (labelsBuilder_.isEmpty()) {
                            labelsBuilder_.dispose();
                            labelsBuilder_ = null;
                            labels_ = other.labels_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                            labelsBuilder_ =
                                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                            getLabelsFieldBuilder() : null;
                        } else {
                            labelsBuilder_.addAllMessages(other.labels_);
                        }
                    }
                }
                if (samplesBuilder_ == null) {
                    if (!other.samples_.isEmpty()) {
                        if (samples_.isEmpty()) {
                            samples_ = other.samples_;
                            bitField0_ = (bitField0_ & ~0x00000002);
                        } else {
                            ensureSamplesIsMutable();
                            samples_.addAll(other.samples_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.samples_.isEmpty()) {
                        if (samplesBuilder_.isEmpty()) {
                            samplesBuilder_.dispose();
                            samplesBuilder_ = null;
                            samples_ = other.samples_;
                            bitField0_ = (bitField0_ & ~0x00000002);
                            samplesBuilder_ =
                                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                            getSamplesFieldBuilder() : null;
                        } else {
                            samplesBuilder_.addAllMessages(other.samples_);
                        }
                    }
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                TimeSeries parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (TimeSeries) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private java.util.List<Label> labels_ =
                    java.util.Collections.emptyList();
            private void ensureLabelsIsMutable() {
                if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                    labels_ = new java.util.ArrayList<Label>(labels_);
                    bitField0_ |= 0x00000001;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    Label, Label.Builder, LabelOrBuilder> labelsBuilder_;

            /**
             * <code>repeated .prometheus.Label labels = 1;</code>
             */
            public java.util.List<Label> getLabelsList() {
                if (labelsBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(labels_);
                } else {
                    return labelsBuilder_.getMessageList();
                }
            }
            /**
             * <code>repeated .prometheus.Label labels = 1;</code>
             */
            public int getLabelsCount() {
                if (labelsBuilder_ == null) {
                    return labels_.size();
                } else {
                    return labelsBuilder_.getCount();
                }
            }
            /**
             * <code>repeated .prometheus.Label labels = 1;</code>
             */
            public Label getLabels(int index) {
                if (labelsBuilder_ == null) {
                    return labels_.get(index);
                } else {
                    return labelsBuilder_.getMessage(index);
                }
            }
            /**
             * <code>repeated .prometheus.Label labels = 1;</code>
             */
            public Builder setLabels(
                    int index, Label value) {
                if (labelsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureLabelsIsMutable();
                    labels_.set(index, value);
                    onChanged();
                } else {
                    labelsBuilder_.setMessage(index, value);
                }
                return this;
            }
            /**
             * <code>repeated .prometheus.Label labels = 1;</code>
             */
            public Builder setLabels(
                    int index, Label.Builder builderForValue) {
                if (labelsBuilder_ == null) {
                    ensureLabelsIsMutable();
                    labels_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    labelsBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .prometheus.Label labels = 1;</code>
             */
            public Builder addLabels(Label value) {
                if (labelsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureLabelsIsMutable();
                    labels_.add(value);
                    onChanged();
                } else {
                    labelsBuilder_.addMessage(value);
                }
                return this;
            }
            /**
             * <code>repeated .prometheus.Label labels = 1;</code>
             */
            public Builder addLabels(
                    int index, Label value) {
                if (labelsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureLabelsIsMutable();
                    labels_.add(index, value);
                    onChanged();
                } else {
                    labelsBuilder_.addMessage(index, value);
                }
                return this;
            }
            /**
             * <code>repeated .prometheus.Label labels = 1;</code>
             */
            public Builder addLabels(
                    Label.Builder builderForValue) {
                if (labelsBuilder_ == null) {
                    ensureLabelsIsMutable();
                    labels_.add(builderForValue.build());
                    onChanged();
                } else {
                    labelsBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .prometheus.Label labels = 1;</code>
             */
            public Builder addLabels(
                    int index, Label.Builder builderForValue) {
                if (labelsBuilder_ == null) {
                    ensureLabelsIsMutable();
                    labels_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    labelsBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .prometheus.Label labels = 1;</code>
             */
            public Builder addAllLabels(
                    Iterable<? extends Label> values) {
                if (labelsBuilder_ == null) {
                    ensureLabelsIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, labels_);
                    onChanged();
                } else {
                    labelsBuilder_.addAllMessages(values);
                }
                return this;
            }
            /**
             * <code>repeated .prometheus.Label labels = 1;</code>
             */
            public Builder clearLabels() {
                if (labelsBuilder_ == null) {
                    labels_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                    onChanged();
                } else {
                    labelsBuilder_.clear();
                }
                return this;
            }
            /**
             * <code>repeated .prometheus.Label labels = 1;</code>
             */
            public Builder removeLabels(int index) {
                if (labelsBuilder_ == null) {
                    ensureLabelsIsMutable();
                    labels_.remove(index);
                    onChanged();
                } else {
                    labelsBuilder_.remove(index);
                }
                return this;
            }
            /**
             * <code>repeated .prometheus.Label labels = 1;</code>
             */
            public Label.Builder getLabelsBuilder(
                    int index) {
                return getLabelsFieldBuilder().getBuilder(index);
            }
            /**
             * <code>repeated .prometheus.Label labels = 1;</code>
             */
            public LabelOrBuilder getLabelsOrBuilder(
                    int index) {
                if (labelsBuilder_ == null) {
                    return labels_.get(index);  } else {
                    return labelsBuilder_.getMessageOrBuilder(index);
                }
            }
            /**
             * <code>repeated .prometheus.Label labels = 1;</code>
             */
            public java.util.List<? extends LabelOrBuilder>
            getLabelsOrBuilderList() {
                if (labelsBuilder_ != null) {
                    return labelsBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(labels_);
                }
            }
            /**
             * <code>repeated .prometheus.Label labels = 1;</code>
             */
            public Label.Builder addLabelsBuilder() {
                return getLabelsFieldBuilder().addBuilder(
                        Label.getDefaultInstance());
            }
            /**
             * <code>repeated .prometheus.Label labels = 1;</code>
             */
            public Label.Builder addLabelsBuilder(
                    int index) {
                return getLabelsFieldBuilder().addBuilder(
                        index, Label.getDefaultInstance());
            }
            /**
             * <code>repeated .prometheus.Label labels = 1;</code>
             */
            public java.util.List<Label.Builder>
            getLabelsBuilderList() {
                return getLabelsFieldBuilder().getBuilderList();
            }
            private com.google.protobuf.RepeatedFieldBuilderV3<
                    Label, Label.Builder, LabelOrBuilder>
            getLabelsFieldBuilder() {
                if (labelsBuilder_ == null) {
                    labelsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                            Label, Label.Builder, LabelOrBuilder>(
                            labels_,
                            ((bitField0_ & 0x00000001) == 0x00000001),
                            getParentForChildren(),
                            isClean());
                    labels_ = null;
                }
                return labelsBuilder_;
            }

            private java.util.List<Sample> samples_ =
                    java.util.Collections.emptyList();
            private void ensureSamplesIsMutable() {
                if (!((bitField0_ & 0x00000002) == 0x00000002)) {
                    samples_ = new java.util.ArrayList<Sample>(samples_);
                    bitField0_ |= 0x00000002;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    Sample, Sample.Builder, SampleOrBuilder> samplesBuilder_;

            /**
             * <code>repeated .prometheus.Sample samples = 2;</code>
             */
            public java.util.List<Sample> getSamplesList() {
                if (samplesBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(samples_);
                } else {
                    return samplesBuilder_.getMessageList();
                }
            }
            /**
             * <code>repeated .prometheus.Sample samples = 2;</code>
             */
            public int getSamplesCount() {
                if (samplesBuilder_ == null) {
                    return samples_.size();
                } else {
                    return samplesBuilder_.getCount();
                }
            }
            /**
             * <code>repeated .prometheus.Sample samples = 2;</code>
             */
            public Sample getSamples(int index) {
                if (samplesBuilder_ == null) {
                    return samples_.get(index);
                } else {
                    return samplesBuilder_.getMessage(index);
                }
            }
            /**
             * <code>repeated .prometheus.Sample samples = 2;</code>
             */
            public Builder setSamples(
                    int index, Sample value) {
                if (samplesBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureSamplesIsMutable();
                    samples_.set(index, value);
                    onChanged();
                } else {
                    samplesBuilder_.setMessage(index, value);
                }
                return this;
            }
            /**
             * <code>repeated .prometheus.Sample samples = 2;</code>
             */
            public Builder setSamples(
                    int index, Sample.Builder builderForValue) {
                if (samplesBuilder_ == null) {
                    ensureSamplesIsMutable();
                    samples_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    samplesBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .prometheus.Sample samples = 2;</code>
             */
            public Builder addSamples(Sample value) {
                if (samplesBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureSamplesIsMutable();
                    samples_.add(value);
                    onChanged();
                } else {
                    samplesBuilder_.addMessage(value);
                }
                return this;
            }
            /**
             * <code>repeated .prometheus.Sample samples = 2;</code>
             */
            public Builder addSamples(
                    int index, Sample value) {
                if (samplesBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureSamplesIsMutable();
                    samples_.add(index, value);
                    onChanged();
                } else {
                    samplesBuilder_.addMessage(index, value);
                }
                return this;
            }
            /**
             * <code>repeated .prometheus.Sample samples = 2;</code>
             */
            public Builder addSamples(
                    Sample.Builder builderForValue) {
                if (samplesBuilder_ == null) {
                    ensureSamplesIsMutable();
                    samples_.add(builderForValue.build());
                    onChanged();
                } else {
                    samplesBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .prometheus.Sample samples = 2;</code>
             */
            public Builder addSamples(
                    int index, Sample.Builder builderForValue) {
                if (samplesBuilder_ == null) {
                    ensureSamplesIsMutable();
                    samples_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    samplesBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .prometheus.Sample samples = 2;</code>
             */
            public Builder addAllSamples(
                    Iterable<? extends Sample> values) {
                if (samplesBuilder_ == null) {
                    ensureSamplesIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, samples_);
                    onChanged();
                } else {
                    samplesBuilder_.addAllMessages(values);
                }
                return this;
            }
            /**
             * <code>repeated .prometheus.Sample samples = 2;</code>
             */
            public Builder clearSamples() {
                if (samplesBuilder_ == null) {
                    samples_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000002);
                    onChanged();
                } else {
                    samplesBuilder_.clear();
                }
                return this;
            }
            /**
             * <code>repeated .prometheus.Sample samples = 2;</code>
             */
            public Builder removeSamples(int index) {
                if (samplesBuilder_ == null) {
                    ensureSamplesIsMutable();
                    samples_.remove(index);
                    onChanged();
                } else {
                    samplesBuilder_.remove(index);
                }
                return this;
            }
            /**
             * <code>repeated .prometheus.Sample samples = 2;</code>
             */
            public Sample.Builder getSamplesBuilder(
                    int index) {
                return getSamplesFieldBuilder().getBuilder(index);
            }
            /**
             * <code>repeated .prometheus.Sample samples = 2;</code>
             */
            public SampleOrBuilder getSamplesOrBuilder(
                    int index) {
                if (samplesBuilder_ == null) {
                    return samples_.get(index);  } else {
                    return samplesBuilder_.getMessageOrBuilder(index);
                }
            }
            /**
             * <code>repeated .prometheus.Sample samples = 2;</code>
             */
            public java.util.List<? extends SampleOrBuilder>
            getSamplesOrBuilderList() {
                if (samplesBuilder_ != null) {
                    return samplesBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(samples_);
                }
            }
            /**
             * <code>repeated .prometheus.Sample samples = 2;</code>
             */
            public Sample.Builder addSamplesBuilder() {
                return getSamplesFieldBuilder().addBuilder(
                        Sample.getDefaultInstance());
            }
            /**
             * <code>repeated .prometheus.Sample samples = 2;</code>
             */
            public Sample.Builder addSamplesBuilder(
                    int index) {
                return getSamplesFieldBuilder().addBuilder(
                        index, Sample.getDefaultInstance());
            }
            /**
             * <code>repeated .prometheus.Sample samples = 2;</code>
             */
            public java.util.List<Sample.Builder>
            getSamplesBuilderList() {
                return getSamplesFieldBuilder().getBuilderList();
            }
            private com.google.protobuf.RepeatedFieldBuilderV3<
                    Sample, Sample.Builder, SampleOrBuilder>
            getSamplesFieldBuilder() {
                if (samplesBuilder_ == null) {
                    samplesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                            Sample, Sample.Builder, SampleOrBuilder>(
                            samples_,
                            ((bitField0_ & 0x00000002) == 0x00000002),
                            getParentForChildren(),
                            isClean());
                    samples_ = null;
                }
                return samplesBuilder_;
            }
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:prometheus.TimeSeries)
        }

        // @@protoc_insertion_point(class_scope:prometheus.TimeSeries)
        private static final TimeSeries DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new TimeSeries();
        }

        public static TimeSeries getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<TimeSeries>
                PARSER = new com.google.protobuf.AbstractParser<TimeSeries>() {
            public TimeSeries parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new TimeSeries(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<TimeSeries> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<TimeSeries> getParserForType() {
            return PARSER;
        }

        public TimeSeries getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface LabelOrBuilder extends
            // @@protoc_insertion_point(interface_extends:prometheus.Label)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string name = 1;</code>
         */
        String getName();
        /**
         * <code>optional string name = 1;</code>
         */
        com.google.protobuf.ByteString
        getNameBytes();

        /**
         * <code>optional string value = 2;</code>
         */
        String getValue();
        /**
         * <code>optional string value = 2;</code>
         */
        com.google.protobuf.ByteString
        getValueBytes();
    }
    /**
     * Protobuf type {@code prometheus.Label}
     */
    public  static final class Label extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:prometheus.Label)
            LabelOrBuilder {
        // Use Label.newBuilder() to construct.
        private Label(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Label() {
            name_ = "";
            value_ = "";
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }
        private Label(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            name_ = s;
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            value_ = s;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Types.internal_static_prometheus_Label_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Types.internal_static_prometheus_Label_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Label.class, Builder.class);
        }

        public static final int NAME_FIELD_NUMBER = 1;
        private volatile Object name_;
        /**
         * <code>optional string name = 1;</code>
         */
        public String getName() {
            Object ref = name_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }
        /**
         * <code>optional string name = 1;</code>
         */
        public com.google.protobuf.ByteString
        getNameBytes() {
            Object ref = name_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int VALUE_FIELD_NUMBER = 2;
        private volatile Object value_;
        /**
         * <code>optional string value = 2;</code>
         */
        public String getValue() {
            Object ref = value_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                value_ = s;
                return s;
            }
        }
        /**
         * <code>optional string value = 2;</code>
         */
        public com.google.protobuf.ByteString
        getValueBytes() {
            Object ref = value_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                value_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
            }
            if (!getValueBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
            }
            if (!getValueBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Label)) {
                return super.equals(obj);
            }
            Label other = (Label) obj;

            boolean result = true;
            result = result && getName()
                    .equals(other.getName());
            result = result && getValue()
                    .equals(other.getValue());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (37 * hash) + VALUE_FIELD_NUMBER;
            hash = (53 * hash) + getValue().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Label parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Label parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Label parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Label parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Label parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Label parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static Label parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static Label parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static Label parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Label parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(Label prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code prometheus.Label}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:prometheus.Label)
                LabelOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Types.internal_static_prometheus_Label_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Types.internal_static_prometheus_Label_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Label.class, Builder.class);
            }

            // Construct using io.logz.listener.inputs.prometheus.protocol.Types.Label.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            public Builder clear() {
                super.clear();
                name_ = "";

                value_ = "";

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Types.internal_static_prometheus_Label_descriptor;
            }

            public Label getDefaultInstanceForType() {
                return Label.getDefaultInstance();
            }

            public Label build() {
                Label result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public Label buildPartial() {
                Label result = new Label(this);
                result.name_ = name_;
                result.value_ = value_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Label) {
                    return mergeFrom((Label)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Label other) {
                if (other == Label.getDefaultInstance()) return this;
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    onChanged();
                }
                if (!other.getValue().isEmpty()) {
                    value_ = other.value_;
                    onChanged();
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Label parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Label) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private Object name_ = "";
            /**
             * <code>optional string name = 1;</code>
             */
            public String getName() {
                Object ref = name_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            /**
             * <code>optional string name = 1;</code>
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>optional string name = 1;</code>
             */
            public Builder setName(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                name_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional string name = 1;</code>
             */
            public Builder clearName() {

                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }
            /**
             * <code>optional string name = 1;</code>
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                name_ = value;
                onChanged();
                return this;
            }

            private Object value_ = "";
            /**
             * <code>optional string value = 2;</code>
             */
            public String getValue() {
                Object ref = value_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    value_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            /**
             * <code>optional string value = 2;</code>
             */
            public com.google.protobuf.ByteString
            getValueBytes() {
                Object ref = value_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    value_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>optional string value = 2;</code>
             */
            public Builder setValue(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                value_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional string value = 2;</code>
             */
            public Builder clearValue() {

                value_ = getDefaultInstance().getValue();
                onChanged();
                return this;
            }
            /**
             * <code>optional string value = 2;</code>
             */
            public Builder setValueBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                value_ = value;
                onChanged();
                return this;
            }
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:prometheus.Label)
        }

        // @@protoc_insertion_point(class_scope:prometheus.Label)
        private static final Label DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new Label();
        }

        public static Label getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Label>
                PARSER = new com.google.protobuf.AbstractParser<Label>() {
            public Label parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Label(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Label> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<Label> getParserForType() {
            return PARSER;
        }

        public Label getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_prometheus_Sample_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_prometheus_Sample_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_prometheus_TimeSeries_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_prometheus_TimeSeries_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_prometheus_Label_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_prometheus_Label_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        String[] descriptorData = {
                "\n\013types.proto\022\nprometheus\"0\n\006Sample\022\r\n\005v" +
                        "alue\030\001 \001(\001\022\027\n\017timestampMillis\030\002 \001(\003\"T\n\nT" +
                        "imeSeries\022!\n\006labels\030\001 \003(\0132\021.prometheus.L" +
                        "abel\022#\n\007samples\030\002 \003(\0132\022.prometheus.Sampl" +
                        "e\"$\n\005Label\022\014\n\004name\030\001 \001(\t\022\r\n\005value\030\002 \001(\tB" +
                        "-\n+io.logz.listener.inputs.prometheus.pr" +
                        "otocolb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_prometheus_Sample_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_prometheus_Sample_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_prometheus_Sample_descriptor,
                new String[] { "Value", "TimestampMillis", });
        internal_static_prometheus_TimeSeries_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_prometheus_TimeSeries_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_prometheus_TimeSeries_descriptor,
                new String[] { "Labels", "Samples", });
        internal_static_prometheus_Label_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_prometheus_Label_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_prometheus_Label_descriptor,
                new String[] { "Name", "Value", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
