name: CI
on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      matrix:
        java: [ '8', '11', '13', '15' ]
    name: Test with Java ${{ matrix.Java }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: '${{ matrix.java }}'
          distribution: 'adopt'
      - name: Test with Gradle
        run: gradle test
