name: Java CI with Gradle
on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      matrix:
        java: [ '8', '11', '13', '15' ]
    name: Java ${{ matrix.Java }} sample
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: '${{ matrix.java }}'
          distribution: 'adopt'
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
      - name: Test with Gradle
        run: gradle test
